name: Engine Health Test

# Controls when the action will run.
on:
  # Triggers the workflow on pull request events but only for the engine base branch and with changes in the src/engine/ directory.
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    paths:
      - 'src/engine/**'
      - '.github/workflows/engine_health_test.yml'

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

# Ensures only one instance of this workflow is running per PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  BUILD_TYPE: Release
  ENGINE_DIR: ${{github.workspace}}/src/engine

jobs:
  build:
    name: Engine Health Test

    # Runs only if the PR status is different to Draft
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Cache CMake and ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.workflow }}-${{ runner.os }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      # Install behave
      run: |
        pip install ${{env.ENGINE_DIR}}/tools/api-communication/
        pip install ${{env.ENGINE_DIR}}/test/integration_tests/it-utils/
        pip install ${{env.ENGINE_DIR}}/tools/engine-suite/

    - name: Setup VCPKG
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: '${{env.ENGINE_DIR}}/vcpkg'
        vcpkgGitCommitId: 'a42af01b72c28a8e1d7b48107b33e4f286a55ef6'
        vcpkgJsonGlob: '${{env.ENGINE_DIR}}/vcpkg.json'

    - name: Configure CMake
      # Configure the CMake build system with the specified build type
      run: cmake --preset=default --no-warn-unused-cli -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S ${{env.ENGINE_DIR}}

    - name: Build
      # Build the specified target using CMake
      run: cmake --build ${{env.ENGINE_DIR}}/build --config ${{env.BUILD_TYPE}} --target main -j$(nproc)

    - name: Setup environment
      # Set Engine Configuration
      run: python3 ${{env.ENGINE_DIR}}/test/setupEnvironment.py -e /tmp/actions

    - name: Initial state
      run: python3 ${{env.ENGINE_DIR}}/test/health_test/initialState.py -e /tmp/actions

    - name: Health Test
      # Run integration tests using behave
      run: python3 ${{env.ENGINE_DIR}}/test/health_test/run.py -e /tmp/actions
