name: Syscollector test on Ubuntu

on:
  pull_request:
    paths:
        - ".github/workflows/ubuntu-syscollector-tests.yml"
        - "src/data_provider/**"
        - "src/shared_modules/**"
        - "src/wazuh_modules/syscollector/**"
        - "src/Makefile"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      # Build wazuh agent for linux.
      - name: Build wazuh agent for linux
        run: |
          rm -rf src/VERSION
          make deps -C src TARGET=agent -j2
          make -C src build_syscollector TARGET=agent -j2
      - name: Install dependencies
        run: |
          pip install -r src/data_provider/qa/requirements.txt
      - name: Run tests
        run: |
          cd src/data_provider
          python -m pytest -vv qa/
