# ~/FUNDING.yml
# -------------
# Copyright (C) 2025 Qompass AI, All rights reserved

github: phaedrusflow
liberapay: qompassai
patreon: qompassai
open_collective: qompassai
custom: ["https://www.buymeacoffee.com/phaedrusflow"]
"monero:42HGspSFJQ4MjM5ZusAiKZj9JZWhfNgVraKb1eGCsHoC6QJqpo2ERCBZDhhKfByVjECernQ6KeZwFcnq8hVwTTnD8v4PzyH"
]
