name: Health
on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, labeled, unlabeled]
jobs:
  health:
    uses: dart-lang/ecosystem/.github/workflows/health.yaml@9fabe464ea1d8408774de74d2ac759c1f90ae480
    with:
      checks: "version,changelog,license,do-not-submit,breaking,coverage,leaking"
    permissions:
      pull-requests: write