# CMake generated Testfile for 
# Source directory: /home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/test
# Build directory: /home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/scripts/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(oqs_signatures "/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/scripts/test/oqs_test_signatures" "oqsprovider" "/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/test/oqs.cnf")
set_tests_properties(oqs_signatures PROPERTIES  ENVIRONMENT "OPENSSL_MODULES=/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/scripts/lib" _BACKTRACE_TRIPLES "/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/test/CMakeLists.txt;8;add_test;/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/test/CMakeLists.txt;0;")
add_test(oqs_kems "/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/scripts/test/oqs_test_kems" "oqsprovider" "/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/test/oqs.cnf")
set_tests_properties(oqs_kems PROPERTIES  ENVIRONMENT "OPENSSL_MODULES=/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/scripts/lib" _BACKTRACE_TRIPLES "/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/test/CMakeLists.txt;29;add_test;/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/test/CMakeLists.txt;0;")
add_test(oqs_groups "/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/scripts/test/oqs_test_groups" "oqsprovider" "/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/test/oqs.cnf" "/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/test")
set_tests_properties(oqs_groups PROPERTIES  ENVIRONMENT "OPENSSL_MODULES=/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/scripts/lib" _BACKTRACE_TRIPLES "/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/test/CMakeLists.txt;50;add_test;/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/test/CMakeLists.txt;0;")
add_test(oqs_tlssig "/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/scripts/test/oqs_test_tlssig" "oqsprovider" "/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/test/openssl-ca.cnf" "/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/scripts/test/tmp")
set_tests_properties(oqs_tlssig PROPERTIES  ENVIRONMENT "OPENSSL_MODULES=/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/scripts/lib" WORKING_DIRECTORY "/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/scripts" _BACKTRACE_TRIPLES "/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/test/CMakeLists.txt;71;add_test;/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/test/CMakeLists.txt;0;")
add_test(oqs_endecode "/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/scripts/test/oqs_test_endecode" "oqsprovider" "/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/test/openssl-ca.cnf")
set_tests_properties(oqs_endecode PROPERTIES  ENVIRONMENT "OPENSSL_MODULES=/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/scripts/lib" _BACKTRACE_TRIPLES "/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/test/CMakeLists.txt;95;add_test;/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/test/CMakeLists.txt;0;")
add_test(oqs_evp_pkey_params "/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/scripts/test/oqs_test_evp_pkey_params" "oqsprovider" "/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/test/openssl-ca.cnf")
set_tests_properties(oqs_evp_pkey_params PROPERTIES  ENVIRONMENT "OPENSSL_MODULES=/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/scripts/lib" _BACKTRACE_TRIPLES "/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/test/CMakeLists.txt;116;add_test;/home/phaedrus/Forge/GH/Qompass/Nautilus/BlueTeam/QompaSSL/oqs-provider/test/CMakeLists.txt;0;")
