name: Tests for ref implementation

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hash:
          - sha2
          - shake
          - haraka
        size:
          - 128
          - 192
          - 256
        option:
          - s
          - f
        thash:
          - simple
          - robust
    steps:
      - uses: actions/checkout@v1
      - name: Run make
        run: |
          make -C ref HASH=${{ matrix.hash }} THASH=${{ matrix.thash }} clean
          make -C ref HASH=${{ matrix.hash }} THASH=${{ matrix.thash }} PARAMS=sphincs-${{ matrix.hash }}-${{ matrix.size }}${{ matrix.option }} tests
          make -C ref HASH=${{ matrix.hash }} THASH=${{ matrix.thash }} PARAMS=sphincs-${{ matrix.hash }}-${{ matrix.size }}${{ matrix.option }} test
          make -C ref THASH=${{ matrix.thash }} PQCgenKAT_sign
      - name: Run PQCgenKAT_sign
        run: python3 vectors.py sphincs-${{ matrix.hash }}-${{ matrix.size }}${{ matrix.option }}-${{ matrix.thash }} ref

#  vim: set ft=yaml ts=2 sw=2 et :
