name: "Publish to FlakeHub"
on:
  push:
    branches: [main, master]
    tags: ["v*"]
  pull_request:
    branches: [main, master]

jobs:
  flakehub-publish:
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check if flake.nix exists
        id: check_flake
        run: |
          if [ -f "flake.nix" ]; then
            echo "has_flake=true" >> $GITHUB_OUTPUT
          else
            echo "has_flake=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish to FlakeHub
        if: steps.check_flake.outputs.has_flake == 'true'
        uses: DeterminateSystems/flakehub-push@main
        with:
          visibility: public
          rolling: true

      - name: Skip - No flake.nix found
        if: steps.check_flake.outputs.has_flake == 'false'
        run: echo "No flake.nix found, skipping FlakeHub publish"
